name: CI/CD Tutorial
on:
    push:
        branches: [main]
        paths:
            - factorial.py
            - lint.py

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                python-version: 3.8
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip 
                pip install --upgrade pylint
            - name: Lint with pylint 
              run: |
                python lint.py